---
# service definition.
# this service will select any pod that has a label service=kubespark-service.
# the service targets port 4567 and exposes itself on port 30568.
apiVersion: v1
kind: Service
metadata:
  name: configmap
  namespace: default
spec:
  selector:
    service: kubespark-service
  ports:
  - port: 4567
    targetPort: 4567
    nodePort: 30568
  # there is no external load balancer, but this type will create a NodePort as well.
  type: LoadBalancer

---
# deployment definition for the pods.
# Pods in this deployment get the label service=kubespark-service.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example-configmap
#  labels:
#    serviceType: kubespark-app
spec:
  replicas: 2
  template:
    metadata:
      name: kubespark
      labels:
        # this label is used by the Service to select the pods
        service: kubespark-service
    spec:
      containers:
      - name: kubespark
        image: kubespark:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4567
        # mount the volume called 'application-config' on the path '/config'.
        volumeMounts:
        - name: application-config
          mountPath: "/config"
          readOnly: true
        # set an environment variable pointing to where the config data ended up.
        env:
        - name: CONFIGLOC
          value: /config/application.json

      # define a volume named 'application-config' and point it to the
      # configmap called 'greet-config'.
      # the item called 'configuration.json' gets the path 'application.json' on the volume.
      volumes:
      - name: application-config
        configMap:
          name: greet-config
          items:
          - key: configuration.json
            path: application.json

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greet-config
  namespace: default
data:
  configuration.json: |
    { "greeting" : "greeting from configmap" }