---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple
  labels:
    serviceType: kubespark-app
spec:
  replicas: 1
  template:
    metadata:
      name: kubespark
      labels:
        serviceType: kubespark-app
    spec:
      containers:
      - name: kubespark
        image: kubespark:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: simple
  namespace: default
spec:
  selector:
    serviceType: kubespark-app
  ports:
  - port: 4567
    targetPort: 4567
    nodePort: 30567
  type: NodePort