---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple
  labels:
    # the label below is not used in this deployment
    serviceType: kubespark-app
spec:
  replicas: 1
  template:
    metadata:
      name: kubespark
      labels:
        # the service definition targets any pod with a matching name=value pair:
        # here the label is "serviceType=kubespark-app" but "foo=bar" would work just as well.
        serviceType: kubespark-app
    spec:
      containers:
      - name: kubespark
        image: kubespark:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: simple
  namespace: default
spec:
  selector:
    # match on Pods which have this label=value pair
    serviceType: kubespark-app
  ports:
  - port: 4567
    targetPort: 4567
    nodePort: 30567
  type: NodePort