---
apiVersion: v1
kind: Service
metadata:
  name: kubespark-entrypointc
  namespace: default
spec:
  selector:
    serviceType: kubespark-appc
  ports:
    - port: 4567
      targetPort: 4567
      nodePort: 30568
  type: NodePort