---
apiVersion: v1
kind: Service
metadata:
  name: kubespark-entrypoint
  namespace: default
spec:
  selector:
    serviceType: kubespark-app
  ports:
    - port: 4567
      targetPort: 4567
      nodePort: 30567
  type: NodePort